language: rust
rust:
  - stable
  - nightly
cache: cargo
services: docker
git:
  depth: 1
env:
  - DATABASE_URL: postgres://postgres@localhost:5433/postgres
before_script:
  - cp Settings.toml.sample Settings.toml
  - ./docker/run.sh
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      before_script: rustup component add rustfmt-preview
      script: cargo fmt -- --check
      env:
    - rust: nightly
      before_script: rustup component add clippy-preview
      script: cargo clippy
      env:
script:
  - cargo build
  - cargo test
notifications:
  email: false
