apiVersion: v1
kind: Service
metadata:
  name: iam-headless
  labels:
    app: iam-headless
spec:
  selector:
    app: iam
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  clusterIP: None

